### ISSUE TITLE
Code Not Saved Properly 

### ISSUE THREAD

**Issue by tanyareuben** [EnsembleUI/ensemble_ts_interpreter#22]
I was working on the code yesterday (June 8th, 2023) and wrote a couple functions. I think around 3 to 4 functions. I also wrote code to test out the functions right after in the body of the Tile. It wasn’t working yet, but I was planning to debug after I took break. I saved my code and went to eat food. When I opened the code again later to work on it, it didn’t save any of the functions I wrote, but it saved the code I wrote after to test the functions in the body. When I look in the history it shows no sign of me writing the code for the 3-4 functions, but it shows the code calling the methods I wrote in the body of the Tile and I really don’t know what happened. 

This image shows the body of the Tile calling the functions I wrote that didn’t save. 
<img width="585" alt="BodyOfTile" src="https://github.com/EnsembleUI/ensemble_ts_interpreter/assets/57576667/81b96a36-b4ad-44b4-afe6-8de237a58eee">

At around 7:31pm is when I started implementing my functions I created into the body of the Tile. At 7:50pm all the methods I wanted to test and had created were all in the body of the Tile.
<img width="147" alt="DifferentTimesOfSaves" src="https://github.com/EnsembleUI/ensemble_ts_interpreter/assets/57576667/4e34e6bb-5722-483e-accc-04a56d7322c7">

At 7:31 on line 120 I started to put the functions I created in the body to test out.
<img width="1432" alt="StartingToImplementFunctionsInBody" src="https://github.com/EnsembleUI/ensemble_ts_interpreter/assets/57576667/6bcada98-6ff6-43a6-9346-cdb887d70aa2">

But when I scroll to the bottom of my code none of the new functions I created are shown. 
<img width="1438" alt="FunctionsNotShownAtFirstSave" src="https://github.com/EnsembleUI/ensemble_ts_interpreter/assets/57576667/34a153c4-b99d-4cd8-a8df-effeb91c46da">

At 7:50pm I have put all the new functions I made to test out (lines 120 to 126). 
<img width="1439" alt="SecondSaveWithAllFunctionsInBody" src="https://github.com/EnsembleUI/ensemble_ts_interpreter/assets/57576667/57746838-e1c3-4816-8b34-57bf41438b30">

But again there is no sign of any of my methods looking like they were done/saved at any point. 
<img width="1440" alt="SecondSaveNoMethodsShownAgain" src="https://github.com/EnsembleUI/ensemble_ts_interpreter/assets/57576667/10ea0544-7aad-4b9f-8e87-e27767c7a1c1">

After running it at 7:50pm I find issues with my method and leave a comment that there is an error to come back and revisit once I’ve had my dinner. I saved it again at 7:51pm. 
<img width="1439" alt="CommentAddedAfterRunningConsoleLogAndFindingError" src="https://github.com/EnsembleUI/ensemble_ts_interpreter/assets/57576667/c6e4b963-fef8-42c8-8673-df3bf586e27a">

But still no sign of my methods ever being saved at any point. 
<img width="1435" alt="ThirdSaveWithNoSignOfFunctionsSaved" src="https://github.com/EnsembleUI/ensemble_ts_interpreter/assets/57576667/2f16a688-a5d4-41bd-b378-84e35d1fe464">

At 10:25pm Ruth made an edit to the GamePlay page, but she commented out some code that had nothing to do with anything I was working on.

Between 7:00pm and 7:03pm I added 2 methods that I ended up deleting shortly after because I figured out a more effective way to write the code (which led to the 3-4 methods that never saved). But the 2 methods I created between 7:00pm and 7:03pm saved and show in the history still.
<img width="625" alt="HistoryShowingSaveOfMethodsThatIDeletedLaterOn" src="https://github.com/EnsembleUI/ensemble_ts_interpreter/assets/57576667/782b1e34-60ef-402d-bf6e-fae3e47c1a30">

I don't know what happened. I find it interesting that it saved the code I wrote after the methods in the body but not the actual methods itself when I saved them both at the same time.

**Comment by amin-nas** [comment]
@tanyareuben thanks for details. I created a new ticket here:
https://github.com/EnsembleUI/ensemble-web-studio/issues/391
