### ISSUE TITLE
No support in JS for setTimeout method

### ISSUE THREAD

**Issue by RuthLHanan** [EnsembleUI/ensemble_ts_interpreter#24]
Primary purpose of setTimeout is to introduce a delay in the execution of code. It allows you to schedule a function or expression to be executed after a specific period of time.
Exp Syntax:
function sayHello() {
  console.log("Hello, world!");
}
setTimeout(sayHello, 2000); //delayed by 2 seconds

**Comment by kmahmood74** [comment]
@vusters this was fixed right?

**Comment by kmahmood74** [comment]
@RuthLHanan use ensemble.startTimer, it is supported.
