### ISSUE TITLE
Support Object properties

### ISSUE THREAD

**Issue by kmahmood74** [EnsembleUI/ensemble_ts_interpreter#36]
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object

Accessing a property of an object already works. 

We still need to support - 

object.keys()
object.values()
object.entries()

Support the for .. in way to iterate over object's properties

**Comment by hemish11** [comment]
Hey @kmahmood74 can't exactly get on what to do

**Comment by kmahmood74** [comment]
run the unit tests - https://github.com/EnsembleUI/ensemble_ts_interpreter/blob/master/test/new_interpreter_tests.dart
and review them, you will see what I mean.
