### ISSUE TITLE
Math.round | JS

### ISSUE THREAD

**Issue by sharjeelyunus** [EnsembleUI/ensemble_ts_interpreter#44]
Math.round is supposed to returns the value of a number rounded to the nearest integer. we mostly use it to round the numbers coming from the api like if its 100.00 or 100.25 we need to show 100

its working on web studio, but not working on build

**Comment by sharjeelyunus** [comment]
`parseInt` doesn't work either on iOS or android. just works on studio

example:
```yaml
- Text:
     text: "${parseInt(getTotalSpent.body.total_spent)}"
```

```yaml
- Text:
     id: price
     text: Rs. ${Math.round(foodItem.price)}
```

```js
function calculatePercentage(number1, number2) {
    if (number1 == 0) {
      return 1;
    } else if (number2 == 0) {
      return 1;
    }
    var ratio = (number1 / number2) * 100;
    var roundedPercentage = Math.round(ratio);
    return roundedPercentage;
  }
  ```

**Comment by kmahmood74** [comment]
it actually works across all platforms. The way you are calling it is incorrect but web is more forgiving. 

When calling Math.round, remember you are dealing with a float and not an int or a string (it's a fraction right). So you have to do `Math.round(parseFloat(foodItem.price))`

also `${parseInt(getTotalSpent.body.total_spent)}` is the `getTotalSpent.body.total_spent` already an int? is it a fraction? in both cases native will throw an exception. 

I'll make the native more forgiving as well just like the web.

**Comment by sharjeelyunus** [comment]
getTotalSpent.body.total_spent is a float like this "100.00" and I want to show it as number => 100

**Comment by kmahmood74** [comment]
fixed, made these functions far more forgiving so the behavior is consistent between web and native and mimics js
